"""
Exports that leave the engine: the approved posting as a Tally import file.

POST, not GET, because an export is an act with a name on it: it is recorded
in the audit trail with who asked for it and whose approval it rests on.
"""

from __future__ import annotations

import re
from datetime import datetime

from fastapi import APIRouter, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel

import audit
import four_eyes
import history
import settlement_qa
import tally_export
from india_tax import ist_date

router = APIRouter()

_APPROVAL = re.compile(r"\[sod actor=(?P<actor>[^|\]]*)\|act=" + four_eyes.ACT_JOURNAL_APPROVAL + r"\]")


class TallyExport(BaseModel):
    reviewer: str
    company: str = ""
    ledgers: dict[str, str] = {}


def latest_result(batch_id: str) -> dict | None:
    """The newest reconciliation of this batch, from this instance or history."""
    found = settlement_qa.get_result(batch_id)
    if found:
        return found
    runs = history.list_runs(limit=1, batch_id=batch_id)
    if runs:
        rec = history.run_detail(runs[0]["record"]) or {}
        return rec.get("result")
    return None


def latest_journal_decision(batch_id: str) -> tuple[str, str] | None:
    """(decision, approver) of the most recent posting decision, if any."""
    for e in reversed(audit.get_audit_trail(batch_id)):
        detail = e.get("detail", "")
        m = _APPROVAL.search(detail)
        if m:
            # The marker holds the name normalised for comparison; the sentence
            # after it holds it as the person typed it, which is what a
            # narration and an audit line should show.
            said = re.match(r"\s*(?P<name>.+?) (?P<act>APPROVED|REJECTED) the posting proposal",
                            detail[m.end():])
            name = said.group("name") if said else m.group("actor")
            approved = said is not None and said.group("act") == "APPROVED"
            return ("approved" if approved else "rejected", name)
    return None


@router.post("/settlement/{batch_id}/export/tally",
             summary="The approved posting as a Tally XML import file")
def export_tally(batch_id: str, body: TallyExport):
    reviewer = (body.reviewer or "").strip()
    if not reviewer:
        raise HTTPException(status_code=422, detail={
            "message": "reviewer is required",
            "plain": "An export is recorded against a name. Sign in first."})

    result = latest_result(batch_id)
    journal = ((result or {}).get("cash_position") or {}).get("journal")
    if not journal:
        raise HTTPException(status_code=409, detail={
            "message": "no posting proposal",
            "plain": ("There is no posting proposal for this batch — it has not been "
                      "reconciled here, or it did not clear, so there is nothing to post.")})
    if not journal.get("balanced") or journal.get("status") == "rejected":
        raise HTTPException(status_code=409, detail={
            "message": "journal does not balance",
            "plain": ("The posting proposal was withheld because it does not balance: "
                      f"{journal.get('rejection_reason') or 'see the journal'}. "
                      "An unbalanced entry is not exported.")})

    decision = latest_journal_decision(batch_id)
    if not decision or decision[0] != "approved":
        raise HTTPException(status_code=409, detail={
            "message": "posting not approved",
            "plain": ("Nobody has approved this posting yet" if not decision else
                      f"The latest decision on this posting was a rejection by {decision[1]}")
                     + ". Tally files are only produced for approved postings, and the "
                       "approver cannot be whoever accepted the match."})

    when = datetime.fromisoformat(journal["date_utc"].replace("Z", "+00:00"))
    try:
        xml = tally_export.journal_to_tally(
            journal, voucher_date=ist_date(when), company=body.company.strip(),
            ledgers=body.ledgers,
            narration=(f"Settlement {batch_id}, reconciled and approved by {decision[1]}. "
                       f"Entry {journal.get('entry_id')}."))
    except ValueError as exc:
        raise HTTPException(status_code=409, detail={"message": "voucher does not balance",
                                                     "plain": str(exc)})
    audit.log_decision(
        batch_id=batch_id, agent="tally_export",
        detail=(f"Tally import file for entry {journal.get('entry_id')} generated by "
                f"{reviewer}, on {decision[1]}'s approval. The engine posted nothing; "
                f"the entry exists in Tally only once someone imports the file."))
    safe = re.sub(r"[^A-Za-z0-9._-]", "_", batch_id)[:80]
    return Response(content=xml, media_type="application/xml", headers={
        "Content-Disposition": f'attachment; filename="tally_{safe}.xml"'})
